###  get request
get http://[::1]:8080/imoveis

###  pagination
get http://192.168.0.129:8080/imoveis?_page=1&_limit=5


###  pagination
get http://192.168.0.129:8080/imoveis?_page=1&_limit=2

###  Comentarios
get http://192.168.0.129:8080/comentarios


###  Comentarios
post http://192.168.0.129:8080/comentarios
Content-Type: application/json
  {
    "id": "10"
    "imovelId": 1,
    "usuario": {
      "id": "4",
      "nome": "Ivete Sangalo",
      "email": "ivete@email.com"
    },
    "texto": "Muito rápido para o trabalho, alguns motoristas irritantes /  rudes, mas eu sou do sul, então não estou acostumado com isso",
    "data": "2024-06-12T10:15:00Z",
    "nota": 4
  }