
services:

  imoveis:
    build: ./dockerfiles/python
    container_name: imoveis
    hostname: imoveis
    restart: always
    volumes:
      - ./app-service:/servico
    command: python3 /servico/imoveis.py
    ports:
      - "5001:5000"
      
  comentarios:
    build: ./dockerfiles/python
    container_name: comentarios
    hostname: comentarios
    restart: always
    volumes:
      - ./app-service:/servico
    command: python3 /servico/comentarios.py
    ports:
      - "5002:5000"

  likes:
    build: ./dockerfiles/python
    container_name: likes
    hostname: likes
    restart: always
    volumes:
      - ./app-service:/servico
    command: python3 /servico/likes.py
    ports:
      - "5003:5000"

  usuarios:
    build: ./dockerfiles/python
    container_name: usuarios
    hostname: usuarios
    restart: always
    volumes:
      - ./app-service:/servico
    command: python3 /servico/usuarios.py
    ports:
      - "5004:5000"

  arquivos:
    build: ./dockerfiles/nginx
    container_name: arquivos
    hostname: arquivos
    restart: always
    volumes:
      - ./imagens:/usr/share/nginx/html
    ports:
      - "5005:80"

  banco:
    build:
      context: .
      dockerfile: dockerfiles/mongo/Dockerfile
    container_name: banco
    hostname: banco
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./dados:/dados
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    depends_on:
      - banco
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@banco:27017/  
      ME_CONFIG_BASICAUTH: false

 